insert into fur_colors
	values
		(null, 'Branco'),
		(null, 'Preto'),
		(null, 'Cinzento'),
		(null, 'Laranja'),
		(null, 'Castanho'),
		(null, 'Amarelo/dourado'),
		(null, 'Outra');
    
insert into fur_lengths
	values
		(null, 'Longo'),
		(null, 'Medio'),
		(null, 'Curto');
        
insert into sizes
	values
		(null, 'Pequeno'),
		(null, 'Medio'),
		(null, 'Grande');
        

        
insert into nature
	values
		(1, null, 'Gato'),
		(2, null, 'Cão'),
		(null, 1,'Abissínio'),
		(null, 1,'American Wirehair'),
		(null, 1,'Asian'),
		(null, 1,'Australian Mist'),
		(null, 1,'Bobtail Americano'),
		(null, 1,'Bombay'),
		(null, 1,'Burmês'),
		(null, 1,'Burmilla'),
		(null, 1,'Cornish Rex'),
		(null, 1,'Curl Americano'),
		(null, 1,'Devon Rex'),
		(null, 1,'Sphynx'),
		(null, 1,'Egyptian Mau'),
		(null, 1,'German Rex'),
		(null, 1,'Havana'),
		(null, 1,'Khao Manee'),
		(null, 1,'Kurlian Bobtail'),
		(null, 1,'Manx'),
		(null, 1,'Munchkin'),
		(null, 1,'Ocicat'),
		(null, 1,'Oriental'),
		(null, 1,'Peterbald'),
		(null, 1,'Pixiebob'),
		(null, 1,'Russian'),
		(null, 1,'Seychellois'),
		(null, 1,'Siamês'),
		(null, 1,'Singapura'),
		(null, 1,'Snowshoe'),
		(null, 1,'Sokoke'),
		(null, 1,'Angorá Turco'),
		(null, 1,'Bobtail Japonês'),
		(null, 1,'Chartreux'),
		(null, 1,'Gato Bosques da Noruega'),
		(null, 1,'LaPerm'),
		(null, 1,'Maine Coon'),
		(null, 1,'RagaMuffin'),
		(null, 1,'Ragdoll'),
		(null, 1,'Sagrado da Birmânia'),
		(null, 1,'Scottish Straigth'),
		(null, 1,'Selkirk Rex'),
		(null, 1,'Somali'),
		(null, 1,'Van Turco'),
		(null, 1,'Balinês'),
		(null, 1,'Siberiano'),
		(null, 1,'Outra (Gato)'),
        
		(null, 2,'Lulu da Pomerânia / Spitz Alemão'),
		(null, 2,'Airedale Terrier'),
		(null, 2,'American Pit Bull Terrier'),
		(null, 2,'Akita'),
		(null, 2,'American Staffordshire Terrier'),
		(null, 2,'Barbado da Terceira'),
		(null, 2,'Basset Hound'),
		(null, 2,'Beagle'),
		(null, 2,'Bichon Maltês'),
		(null, 2,'Boerboel'),
		(null, 2,'Border Collie'),
		(null, 2,'Boston Terrier'),
		(null, 2,'Boxer'),
		(null, 2,'Braco Alemão '),
		(null, 2,'Bull Terrier'),
		(null, 2,'Bulldog Americano'),
		(null, 2,'Bulldog Francês'),
		(null, 2,'Bulldog Inglês '),
		(null, 2,'BullMastiff'),
		(null, 2,'Cane Corso'),
		(null, 2,'Caniche'),
		(null, 2,'Cão de Castro Laboreiro'),
		(null, 2,'Cão da Serra da Estrela'),
		(null, 2,'Cão da Serra de Aires'),
		(null, 2,'Cão de Água'),
		(null, 2,'Cão de Fila de São Miguel'),
		(null, 2,'Cão de Gado Transmontano '),
		(null, 2,'Chihuahua'),
		(null, 2,'Cão de montanha de Berna'),
		(null, 2,'Cão do Barrocal Algarvio'),
		(null, 2,'Cavalier King Charles Spaniel'),
		(null, 2,'Chow Chow'),
		(null, 2,'CockerSpaniel Inglês'),
		(null, 2,'Dougue Argentino'),
		(null, 2,'Dachshund'),
		(null, 2,'Dalmata'),
		(null, 2,'Dobermann'),
		(null, 2,'Dougue de Bordéus '),
		(null, 2,'English Springer Spaniel'),
		(null, 2,'Galgo'),
		(null, 2,'Golden Retriever'),
		(null, 2,'Grand Danois'),
		(null, 2,'Labrador'),
		(null, 2,'Greyhound'),
		(null, 2,'Husky'),
		(null, 2,'Lhasa Apso'),
		(null, 2,'Pastor Alemão '),
		(null, 2,'Malamute do Alasca'),
		(null, 2,'Pequinês'),
		(null, 2,'Pinscher'),
		(null, 2,'Rottweiler'),
		(null, 2,'Pug'),
		(null, 2,'Rough Collie'),
		(null, 2,'São Bernardo'),
		(null, 2,'Shar Pei'),
		(null, 2,'Schnauzer'),
		(null, 2,'Scottish Terrier'),
		(null, 2,'Shih Tzu'),
		(null, 2,'Weimaraner'),
		(null, 2,'Terra Nova'),
		(null, 2,'Whippet'),
		(null, 2,'Outra (Cão)'),
		(null, 2,'Yorkshire Terrier');
        